{% set version = "4.82" %}

package:
  name: pyro4
  version: {{ version }}

source:
  fn: Pyro4-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/P/Pyro4/Pyro4-{{ version }}.tar.gz
  sha256: 511f5b0804e92dd77dc33adf9c947787e3f9e9c5a96b12162f0557a7c4ce21fb

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pyro4-ns = Pyro4.naming:main
    - pyro4-nsc = Pyro4.nsc:main
    - pyro4-test-echoserver = Pyro4.test.echoserver:main
    - pyro4-check-config = Pyro4.configuration:main
    - pyro4-flameserver = Pyro4.utils.flameserver:main
    - pyro4-httpgateway = Pyro4.utils.httpgateway:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - serpent >=1.27

  run:
    - python >={{ python_min }}
    - serpent >=1.27

test:
  requires:
    - python {{ python_min }}
  imports:
    - Pyro4
    - Pyro4.socketserver
    - Pyro4.test
    - Pyro4.utils

  commands:
    - pyro4-ns --help
    - pyro4-nsc --help
    - pyro4-test-echoserver --help
    - pyro4-check-config --help
    - pyro4-flameserver --help
    - pyro4-httpgateway --help

about:
  home: https://pyro4.readthedocs.io
  license: MIT
  license_file: LICENSE
  summary: Distributed object middleware for Python (RPC)

extra:
  recipe-maintainers:
    - whart222
    - irmen
