{% set version = "4.72" %}

package:
  name: pyro4
  version: {{ version }}

source:
  fn: Pyro4-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/P/Pyro4/Pyro4-{{ version }}.tar.gz
  sha256: 2766b53db49f70b0d047fa6871aeb47484ba7e50cf53cfa37d26f87742c0b6a8

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - pyro4-ns = Pyro4.naming:main
    - pyro4-nsc = Pyro4.nsc:main
    - pyro4-test-echoserver = Pyro4.test.echoserver:main
    - pyro4-check-config = Pyro4.configuration:main
    - pyro4-flameserver = Pyro4.utils.flameserver:main
    - pyro4-httpgateway = Pyro4.utils.httpgateway:main

requirements:
  build:
    - python
    - setuptools
    - serpent >=1.23

  run:
    - python
    - serpent >=1.23

test:
  imports:
    - Pyro4
    - Pyro4.socketserver
    - Pyro4.test
    - Pyro4.utils

  commands:
    - pyro4-ns --help
    - pyro4-nsc --help
    - pyro4-test-echoserver --help
    - pyro4-check-config --help
    - pyro4-flameserver --help
    - pyro4-httpgateway --help

about:
  home: https://pyro4.readthedocs.io
  license: MIT
  summary: 'Distributed object middleware for Python (RPC)'

extra:
  recipe-maintainers:
    - whart222
    - irmen
    - Juanlu001
